### ISSUE TITLE
Request: implement Aircraft/Minicraft Plus features

### ISSUE THREAD

**Issue by nodigit** [Vulcalien/minicraft-gba#6]
This works great but you should implement some of the Aircraft/Minicraft Plus features.

**Comment by Vulcalien** [comment]
Adding more features to the game takes time. Some of them (items and entities in particular) would probably be quite easy to add, while others (tiles!) would be more difficult, because of the hardware limitations of the GBA.

Ultimately, I might consider working on new features in the future, but the original goal of demaking 'Minicraft' has been accomplished.
